const Review = require('../models/Review');
const Bootcamp = require('../models/Bootcamp');
const ErrorResponse = require('../utils/errorResponse');
const asyncHandler = require('../middleware/asyncHandler');


// @desc: Get All Reviews for a Course
// @route: GET /api/v1/bootcamps/:bootcampId/reviews
// @route: GET /api/v1/reviews
// @access: public 
// Using asyncHandler
const getReviews = asyncHandler (async (req, res, next) => {
    // Determine which Route is selected
    // first get the Reviews from only one particular bootcamp, which requires just a simple query
    if (req.params.bootcampId){
        const reviews = await Review.find({bootcamp: req.params.bootcampId});
        return res.status(200).json({success: true, count: reviews.length, data: reviews });
    } else {
        // The second route gets all reviews from all bootcamps which requires a more advanced query and pagination functionality
        // res.queryResults has already been generated by the queryHandler Middleware
        res.status(200).json(res.queryResults);
    }
});

// Exports
// -------
exports.getReviews = getReviews;
